-- Position Sync Cron Job Setup
-- Migration: 20250128_setup_position_sync_cron.sql
-- Sets up a cron job to sync positions from exchange for all running bots

-- =====================================================
-- IMPORTANT: Set POSITION_SYNC_SECRET First
-- =====================================================
-- Before creating the cron schedule, make sure you have set:
-- 1. Go to Supabase Dashboard → Edge Functions → position-sync → Settings
-- 2. Add Environment Variable: POSITION_SYNC_SECRET = [your-secret-value]
-- 3. Save

-- =====================================================
-- Option 1: Using Supabase Dashboard (Recommended)
-- =====================================================
-- 1. Go to Supabase Dashboard → Edge Functions → position-sync
-- 2. Click "Schedules" tab
-- 3. Create new schedule:
--    - Schedule Name: position-sync-schedule
--    - Cron Expression: */5 * * * * (every 5 minutes)
--    - HTTP Method: POST
--    - Headers:
--      Key: x-cron-secret
--      Value: [SAME VALUE as POSITION_SYNC_SECRET environment variable]
--    - Enabled: Yes
-- 4. Save

-- =====================================================
-- Option 2: Using pg_cron (NOT RECOMMENDED - net extension not available)
-- =====================================================
-- NOTE: Supabase does not have the 'net' extension available,
-- so pg_cron cannot make HTTP calls directly.
-- Use Option 1 (Supabase Dashboard) or Option 3 (External Cron) instead.
--
-- If you have pg_cron and want to use it, you would need to:
-- 1. Create a PostgreSQL function that can be called by cron
-- 2. Use an external service to trigger the Edge Function
-- 3. Or use Supabase's built-in cron scheduler (Option 1)

-- =====================================================
-- Option 3: External Cron Job (Alternative)
-- =====================================================
-- If Supabase cron jobs are not available, use external scheduler:
--
-- Add to your server's crontab (crontab -e):
-- 
-- # Position Sync - Every 5 minutes
-- */5 * * * * curl -X POST https://YOUR_PROJECT.supabase.co/functions/v1/position-sync \
--   -H "Authorization: Bearer YOUR_SERVICE_ROLE_KEY" \
--   -H "x-cron-secret: YOUR_CRON_SECRET" \
--   -H "Content-Type: application/json" \
--   -d '{}' \
--   >> /var/log/position-sync.log 2>&1
--
-- Replace:
--   YOUR_PROJECT - Your Supabase project reference
--   YOUR_SERVICE_ROLE_KEY - Get from Supabase Dashboard → Settings → API
--   YOUR_CRON_SECRET - Set in Supabase Edge Function Secrets as CRON_SECRET

-- =====================================================
-- Verification
-- =====================================================

-- Check if cron job is scheduled (if using pg_cron):
-- SELECT * FROM cron.job WHERE jobname = 'position-sync-schedule';

-- Check recent job runs (if using pg_cron):
-- SELECT * FROM cron.job_run_details 
-- WHERE jobid = (SELECT jobid FROM cron.job WHERE jobname = 'position-sync-schedule')
-- ORDER BY start_time DESC LIMIT 10;

-- =====================================================
-- Manual Test
-- =====================================================
-- Test the position sync function manually:
-- 
-- curl -X POST https://YOUR_PROJECT.supabase.co/functions/v1/position-sync \
--   -H "Authorization: Bearer YOUR_SERVICE_ROLE_KEY" \
--   -H "x-cron-secret: YOUR_CRON_SECRET" \
--   -H "Content-Type: application/json" \
--   -d '{}'
