-- =============================================
-- Immediate Trading Bot - Custom Pairs
-- Starts trading immediately when activated from Pablo Ready
-- Supports any custom trading pair
-- =============================================

INSERT INTO public.pablo_ready_bots (
  name,
  description,
  exchange,
  symbol,
  trading_type,
  leverage,
  risk_level,
  strategy,
  strategy_config,
  trade_amount,
  stop_loss,
  take_profit,
  timeframe,
  enabled,
  featured,
  order_index
) VALUES (
  'Immediate Trading Bot - Custom Pairs',
  'Fast-acting bot that starts trading immediately with any custom trading pair. Uses aggressive trend-following strategy with quick entry signals. Optimized for immediate execution and high trade frequency. Perfect for active traders who want instant action.',
  'bybit',
  'CUSTOM', -- Placeholder - user will input their own pair
  'futures',
  3,
  'medium',
  '{"type": "trend_following", "name": "Immediate Trading Bot", "allows_custom_pair": true, "immediate_trading": true}'::jsonb,
  '{
    "bias_mode": "both",
    "regime_mode": "auto",
    "htf_timeframe": "1h",
    "htf_trend_indicator": "EMA50",
    "ema_fast_period": 12,
    "ema_slow_period": 26,
    "require_price_vs_trend": "any",
    "adx_min_htf": 15,
    "require_adx_rising": false,
    "adx_trend_min": 18,
    "adx_meanrev_max": 25,
    "session_filter_enabled": false,
    "allowed_hours_utc": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],
    "cooldown_bars": 2,
    "atr_percentile_min": 10,
    "bb_width_min": 0.008,
    "bb_width_max": 0.08,
    "min_24h_volume_usd": 10000000,
    "max_spread_bps": 8,
    "risk_per_trade_pct": 1.5,
    "daily_loss_limit_pct": 5.0,
    "weekly_loss_limit_pct": 10.0,
    "max_trades_per_day": 20,
    "max_concurrent": 3,
    "max_consecutive_losses": 5,
    "sl_atr_mult": 1.2,
    "tp1_r": 1.5,
    "tp2_r": 3.0,
    "tp1_size": 0.6,
    "tp2_size": 0.4,
    "breakeven_at_r": 0.5,
    "trail_after_tp1_atr": 1.0,
    "time_stop_hours": 24,
    "rsi_period": 14,
    "rsi_oversold": 25,
    "rsi_overbought": 75,
    "atr_period": 14,
    "atr_tp_multiplier": 2.5,
    "momentum_threshold": 0.5,
    "vwap_distance": 0.8,
    "use_ml_prediction": false,
    "min_volume_requirement": 0.3,
    "trend_confirmation_periods": 1,
    "fast_entry": true,
    "immediate_execution": true
  }'::jsonb,
  100,
  1.5,
  3.0,
  '15m',
  true,
  true,
  10
) ON CONFLICT DO NOTHING;

