-- =============================================
-- Add Advanced Dual-Mode Scalping Strategy Bot to Pablo Ready Bots
-- =============================================

INSERT INTO public.pablo_ready_bots (
  name,
  description,
  exchange,
  symbol,
  trading_type,
  leverage,
  risk_level,
  strategy,
  strategy_config,
  trade_amount,
  stop_loss,
  take_profit,
  timeframe,
  enabled,
  featured,
  order_index
) VALUES (
  'Advanced Dual-Mode Scalping Strategy',
  'Professional scalping strategy with two modes: Reversal Scalping (RSI/VWAP bounces) and Trend Continuation Scalping (EMA pullbacks). Uses Supertrend (10,3) on HTF for trend filtering, ATR-based stops, multiple TPs (1R, 1.5R, 2R), and comprehensive risk filters. Optimized for 1m, 3m, 5m timeframes.',
  'bybit',
  'BTCUSDT',
  'futures',
  1,
  'high',
  '{"type": "advanced_scalping", "name": "Advanced Dual-Mode Scalping Strategy", "mode": "auto"}'::jsonb,
  '{
    "timeframe": "3m",
    "htf_timeframe": "30m",
    "htf_trend_indicator": "Supertrend",
    "supertrend_period": 10,
    "supertrend_multiplier": 3.0,
    "scalping_mode": "auto",
    "ema_fast": 9,
    "ema_slow": 21,
    "rsi_period": 14,
    "rsi_oversold": 35,
    "rsi_overbought": 65,
    "rsi_reversal_zone_low": 30,
    "rsi_reversal_zone_high": 70,
    "bb_period": 20,
    "bb_stddev": 2.0,
    "atr_period": 14,
    "atr_sl_multiplier": 1.2,
    "atr_tp1_multiplier": 1.0,
    "atr_tp2_multiplier": 1.5,
    "atr_tp3_multiplier": 2.0,
    "adx_period": 14,
    "adx_min_continuation": 20,
    "volume_multiplier_reversal": 1.5,
    "volume_multiplier_continuation": 1.2,
    "min_volatility_atr_reversal": 0.25,
    "min_volatility_atr_continuation": 0.3,
    "max_volatility_atr": 2.0,
    "bb_width_min": 0.5,
    "bb_width_max": 3.0,
    "tp1_size": 50,
    "tp2_size": 30,
    "tp3_size": 20,
    "breakeven_at_r": 1.0,
    "trailing_stop_atr": 1.0,
    "trailing_stop_activate_after_tp1": true,
    "time_stop_minutes": 30,
    "cooldown_candles": 3,
    "cooldown_same_direction_candles": 5,
    "time_filter_enabled": true,
    "allowed_hours_utc": [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
    "max_concurrent_positions": 2,
    "max_trades_per_day": 20,
    "daily_loss_limit_pct": 3.0,
    "risk_per_trade_pct": 0.75,
    "vwap_period": 20
  }'::jsonb,
  100.00,
  0.4,
  1.0,
  '3m',
  true,
  true,
  4
);

