name: Deploy to Supabase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "🚀 Deploying all Edge Functions..."
          supabase functions deploy bot-executor --no-verify-jwt || true
          supabase functions deploy bot-management --no-verify-jwt || true
          supabase functions deploy admin-management-enhanced --no-verify-jwt || true
          supabase functions deploy trading-engine --no-verify-jwt || true
          supabase functions deploy telegram-notifier --no-verify-jwt || true
          supabase functions deploy market-data --no-verify-jwt || true
          supabase functions deploy ml-predictions --no-verify-jwt || true
          supabase functions deploy alerts-system --no-verify-jwt || true
          supabase functions deploy api-keys --no-verify-jwt || true
          supabase functions deploy profile-management --no-verify-jwt || true
          supabase functions deploy risk-management --no-verify-jwt || true
          supabase functions deploy invitation-management --no-verify-jwt || true
          echo "✅ All functions deployed successfully!"

